In [5]:
import numpy as np
import pandas as pd
from sentence_transformers import SentenceTransformer
import json
import faiss
import joblib

import torch

from sklearn.model_selection import train_test_split

from src.data.rac_utils import pooled_agument_texts, retrive_related
from src.data.datastruct import Sample, Batch
from src.data.collate import collate_func, create_batch, create_samples

In [2]:
# import data and index
device = "cuda" if torch.cuda.is_available() else "cpu"
DATA_PATH = "../data/raw/all_tickets_processed_improved_v3.csv"
df = pd.read_csv(DATA_PATH)
df.head()

X = df["Document"]
y = df["Topic_group"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, shuffle=True, random_state=2)

with open("../artifacts/rac_corpus_similarity-euclidian_index_v01.json", 'r') as f:
    corpus = json.load(f)

similarity_index = faiss.read_index("../artifacts/traindata_similarity_index_v01.index")
euclidian_index = faiss.read_index("../artifacts/traindata_euclidian_index_v01.index")

retrieval_model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2", device=device)

In [3]:
X_train_agumented = pooled_agument_texts(retrieval_model = retrieval_model,
                                        index=similarity_index,
                                        corpus=corpus,
                                        keys=["Document", "Topic_group"],
                                        augmentation_key="Document",
                                        texts=X_train.tolist(),
                                        remove_top=True)

38269it [05:13, 121.90it/s]

In [4]:
X_test_agumented = pooled_agument_texts(retrieval_model = retrieval_model,
                                        index=similarity_index,
                                        corpus=corpus,
                                        keys=["Document", "Topic_group"],
                                        augmentation_key="Document",
                                        texts=X_test.tolist(),
                                        remove_top=True)

9568it [01:20, 118.16it/s]

In [6]:
with open("../data/processed/agumented_ticketdata_similarity_v01.json", 'w') as f:
    json.dump(
        {
            "train": {
                "X": X_train_agumented,
                "y": y_train.tolist()
            },
            "test": {
                "X": X_test_agumented,
                "y": y_test.tolist()
            }
        },
        f
    )

In [7]:
X_train_agumented = pooled_agument_texts(retrieval_model = retrieval_model,
                                        index=euclidian_index,
                                        corpus=corpus,
                                        keys=["Document", "Topic_group"],
                                        augmentation_key="Document",
                                        texts=X_train.tolist(),
                                        remove_top=True)
X_test_agumented = pooled_agument_texts(retrieval_model = retrieval_model,
                                        index=euclidian_index,
                                        corpus=corpus,
                                        keys=["Document", "Topic_group"],
                                        augmentation_key="Document",
                                        texts=X_test.tolist(),
                                        remove_top=True)

38269it [05:49, 109.57it/s]
9568it [01:30, 105.76it/s]

In [8]:
with open("../data/processed/agumented_ticketdata_euclidian_v01.json", 'w') as f:
    json.dump(
        {
            "train": {
                "X": X_train_agumented,
                "y": y_train.tolist()
            },
            "test": {
                "X": X_test_agumented,
                "y": y_test.tolist()
            }
        },
        f
    )

In [13]:
# testing
from tqdm import tqdm

test_retrieval_result_similarity_index = [retrive_related(retrieval_model, similarity_index, text, corpus, ["Document", "Topic_group"], 10) 
                                        for text in tqdm(X_test.tolist())]

test_retrieval_result_euclidian_index = [retrive_related(retrieval_model, euclidian_index, text, corpus, ["Document", "Topic_group"], 10) 
                                        for text in tqdm(X_test.tolist())]

100%|██████████| 9568/9568 [01:55<00:00, 83.01it/s]
100%|██████████| 9568/9568 [01:56<00:00, 82.29it/s]

In [21]:
from collections import Counter
def eval(test_list):
    y_pred = []
    y_pred_score = []
    for _test in tqdm(test_list):
        _counter = Counter()
        _r_y = [_r["Topic_group"] for _r in _test]
        _counter.update(_r_y)
        
        element, count = _counter.most_common(1)[0]
        y_pred.append(element)
        y_pred_score.append(count/len(_test))
    return y_pred, y_pred_score

In [22]:
y_pred_retrieval_result_similarity_index, y_predscore_retrieval_result_similarity_index = eval(test_retrieval_result_similarity_index)

y_pred_retrieval_result_euclidian_index, y_predscore_retrieval_result_euclidian_index = eval(test_retrieval_result_euclidian_index)

100%|██████████| 9568/9568 [00:00<00:00, 211645.18it/s]
100%|██████████| 9568/9568 [00:00<00:00, 215190.55it/s]

In [25]:
from src.evaluation.metrics import format_cm, evaluate
from src.evaluation.neural_eval import evaluate as neural_eval
from sklearn.preprocessing import LabelEncoder


labelencode: LabelEncoder = joblib.load("../artifacts/labelencoder_neural_v01.pkl")

In [27]:
format_cm(evaluate(y_test, y_pred_retrieval_result_similarity_index), class_names=list(labelencode.classes_), normalize=True)

                       precision    recall  f1-score   support

               Access     0.9040    0.8589    0.8809      1425
Administrative rights     0.8456    0.6847    0.7567       352
           HR Support     0.8004    0.8727    0.8350      2183
             Hardware     0.8195    0.8366    0.8280      2724
     Internal Project     0.8395    0.7524    0.7935       424
        Miscellaneous     0.8062    0.7748    0.7902      1412
             Purchase     0.8691    0.9026    0.8856       493
              Storage     0.8998    0.8414    0.8696       555

             accuracy                         0.8334      9568
            macro avg     0.8480    0.8155    0.8299      9568
         weighted avg     0.8348    0.8334    0.8331      9568

,Pred: Access,Pred: Administrative rights,Pred: HR Support,Pred: Hardware,Pred: Internal Project,Pred: Miscellaneous,Pred: Purchase,Pred: Storage
True: Access,0.858947,0.000702,0.050526,0.050526,0.006316,0.023158,0.004211,0.005614
True: Administrative rights,0.019886,0.684659,0.042614,0.193182,0.005682,0.022727,0.028409,0.002841
True: HR Support,0.009162,0.001832,0.872652,0.064132,0.006871,0.038937,0.001832,0.004581
True: Hardware,0.022394,0.011013,0.069016,0.836637,0.004772,0.037812,0.013216,0.005140
True: Internal Project,0.018868,0.007075,0.108491,0.051887,0.752358,0.047170,0.007075,0.007075
True: Miscellaneous,0.015581,0.001416,0.084278,0.094901,0.012040,0.774788,0.005666,0.011331
True: Purchase,0.010142,0.000000,0.024341,0.048682,0.008114,0.006085,0.902637,0.000000
True: Storage,0.012613,0.007207,0.041441,0.075676,0.001802,0.019820,0.000000,0.841441

In [28]:
format_cm(evaluate(y_test, y_pred_retrieval_result_euclidian_index), class_names=list(labelencode.classes_), normalize=True)

                       precision    recall  f1-score   support

               Access     0.9040    0.8589    0.8809      1425
Administrative rights     0.8456    0.6847    0.7567       352
           HR Support     0.8004    0.8727    0.8350      2183
             Hardware     0.8195    0.8366    0.8280      2724
     Internal Project     0.8395    0.7524    0.7935       424
        Miscellaneous     0.8062    0.7748    0.7902      1412
             Purchase     0.8691    0.9026    0.8856       493
              Storage     0.8998    0.8414    0.8696       555

             accuracy                         0.8334      9568
            macro avg     0.8480    0.8155    0.8299      9568
         weighted avg     0.8348    0.8334    0.8331      9568

,Pred: Access,Pred: Administrative rights,Pred: HR Support,Pred: Hardware,Pred: Internal Project,Pred: Miscellaneous,Pred: Purchase,Pred: Storage
True: Access,0.858947,0.000702,0.050526,0.050526,0.006316,0.023158,0.004211,0.005614
True: Administrative rights,0.019886,0.684659,0.042614,0.193182,0.005682,0.022727,0.028409,0.002841
True: HR Support,0.009162,0.001832,0.872652,0.064132,0.006871,0.038937,0.001832,0.004581
True: Hardware,0.022394,0.011013,0.069016,0.836637,0.004772,0.037812,0.013216,0.005140
True: Internal Project,0.018868,0.007075,0.108491,0.051887,0.752358,0.047170,0.007075,0.007075
True: Miscellaneous,0.015581,0.001416,0.084278,0.094901,0.012040,0.774788,0.005666,0.011331
True: Purchase,0.010142,0.000000,0.024341,0.048682,0.008114,0.006085,0.902637,0.000000
True: Storage,0.012613,0.007207,0.041441,0.075676,0.001802,0.019820,0.000000,0.841441